### ISSUE TITLE
Resolving content item links in RichText field

### ISSUE THREAD

**Issue by pauloroque** [vit-svoboda/kontent-rich-text-for-vue#17]
Hi,

Thanks for this awesome tool. Everything is working great so far in our project only for this one issue. The rich text component doesn't seem to be resolving the content item link. Kentico Kontent returns this HTML 

`<p><a data-item-id="dbd3d39b-d59a-488b-91eb-aaca45e8151c" href="">Content Item Link</a></p>`

but it resolves to

`<p><a href="">Content Item Link</a></p>`

Is this expected?

**Comment by vit-svoboda** [comment]
Hey,

I'm glad you find this package useful. Your observation is correct, content item links are not supported yet. I didn't use them in my project and haven't recieved any feedback until now. I'll look into adding the content item link resolution in the upcoming v2.0.0.

**Comment by pauloroque** [comment]
Sorry to ask but do you have a timeline on that? We are about to launch our project at the end of the month and we need to come up with a solution asap.

**Comment by vit-svoboda** [comment]
I'd like to get v2 out of the door by the end of the week.

As for the linked items, I expect to add a parameter where the caller can pass a resolver component similar to the `linkedItemComponent`, but for `<a>` rather than `<object>` from the original HTML.

This can be useful for regular links if the caller wants to add some analytics or whatnot. But most importantly, the caller can translate the content item ID to a link in their web. I need to take a look at the assistance Kontent Delivery SDK provides for this operation and whether I can have that implementation injected or do something similar. Otherwise, the translation could be rather tedious to setup, I'm afraid.

**Comment by vit-svoboda** [comment]
I just released a new preview of v2 with added support for customization of thee rendered links, as well as the `href` attribute of content item links. Please let me know if this works for you.

**Comment by pauloroque** [comment]
Hi,
I tried this using your sample in the readme but I'm getting this error and warning below. Looks like the createLink does not exist. 

 **WARN**  in ./components/BOSInternalPage.vue?vue&type=script&lang=js&                                                                                                       friendly-errors 17:34:51  

"export 'createLink' was not found in 'kontent-rich-text-for-vue'                                                                                                         friendly-errors 17:34:51  
                                                                                                                                                                          friendly-errors 17:34:51  

 **ERROR**  [Vue warn]: Error in render: "TypeError: Object(...) is not a function"         
```

<script>
import RichTextComponent from '~/components/RichTextComponent'
import { RichText, createLink } from 'kontent-rich-text-for-vue'

export default {
  props: ['item'],  
  computed: {
    richTextComponent() {
      return RichTextComponent
    },
    linkComponent: () =>
      createLink({       
        getItemLinkUrl: (itemId) => {
          const { codename, urlSlug, type } = this.page.mainBodyLinks.find(
            (link) => link.linkId === itemId
          )
          return `/${urlSlug}`
          //return this.$getUrlByCodename(codename)
        }
      }),
    page() {
      return this.item
    }
  },
  provide() {
    return {
      getLinkedItems: () => {
        return this.item.linkedItems
      }
    }
  }
}
</script>
```

**Comment by vit-svoboda** [comment]
Right, the exported function is actually called `linkFactory`, I'll fix the readme. I'm sorry about that.

**Comment by pauloroque** [comment]
This is working perfectly. Thanks for the quick fix.

**Comment by vit-svoboda** [comment]
Awesome, in that case I'm going to publish the v2 as final without the preview suffix.
